---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - steam
        - python3-psutil

  - name: copy wallpaper file
    copy:
      src: files/blood_moon_wallpaper.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: tommi
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

  - name: set wallpaper position
    become_user: tommi
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"
